dist: xenial
sudo: required
language: node_js
addons:
  apt:
    update: true
    packages:
      - jq
node_js:
- 10.14.1
before_install:
- openssl aes-256-cbc -K $encrypted_576d8886d7a3_key -iv $encrypted_576d8886d7a3_iv
  -in ci/wiki_deploy_key.enc -out ci/wiki_deploy_key -d
- chmod 600 ci/wiki_deploy_key
script:
- truffle compile
deploy:
  skip_cleanup: true
  provider: script
  script: ci/update_wiki.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^ci|master$
